### ISSUE TITLE
打算出本地搭建的文档吗？

### ISSUE THREAD

**Issue by izhuooo** [MarvenGong/fastmock#12]
大佬大佬，打算出本地搭建的文档吗？数据库该是什么架构啊？

**Comment by MarvenGong** [comment]
后面会出的，可以在网站右上角加我们的qq群跟进哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"izhuooo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月13日(星期五) 晚上8:47
收件人:&nbsp;"MarvenGong/fastmock"<fastmock@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[MarvenGong/fastmock] 打算出本地搭建的文档吗？ (#12)





 
大佬大佬，打算出本地搭建的文档吗？数据库该是什么架构啊？
