### ISSUE TITLE
服务器崩掉了！！！

### ISSUE THREAD

**Issue by lyflyy** [MarvenGong/fastmock#16]
### 服务挂了

**Comment by lyflyy** [comment]
大佬在升级

**Comment by lyflyy** [comment]
领导问我为什么不干活，我说服务器挂掉了。。
	领导当时就把后端开了，补偿了15天的工资，我的心冰凉冰凉的
	有多凉呢，就好像情人节你准备了礼物也定了餐厅，女朋友说要加班，你只好自己在家吃外卖，外卖是凉的，还没给筷子，你凑合吃了，吃完了打了一局排位，这是你的晋级赛，你方鲁班像个活雷锋一样嗷嗷送人头，凯全场不知所措，最后6分钟被人推掉，投降都来不及，你拿了败方mvp，坐在沙发上你百无聊赖听邻居的叫床声，此时你的女朋友微信发来了一张照片，他发错人了，一秒钟就撤回了，但是你看到了，他跟你最好的兄弟小光的自拍合影，亲嘴的那种，那时候你的心，就跟我现在访问fastmock的时候的心脏的温度差不多。

**Comment by lyflyy** [comment]
大佬  你更新服务也太频繁了吧
能否提供一个数据导出的方式  导出接口，我自己部署一套您的服务，您的服务太不稳定了

**Comment by MarvenGong** [comment]
已恢复

**Comment by MarvenGong** [comment]
本地部署文档 地址 https://fmdocs.fastmock.site/book/install-home.html
