### ISSUE TITLE
能否新增查看请求信息日志的功能

### ISSUE THREAD

**Issue by LadyDoDo** [MarvenGong/fastmock#26]
我需要看我请求过来的数据是否正确，想请问是否能添加此功能

**Comment by MarvenGong** [comment]
这个记录成本太高了，您想想，我这边对接了多少用户，每个用户的对应的并发量都有可能很高。尤其是那些用fastmock投入生产使用的

**Comment by tzbcf** [comment]
刚打开Issues也想建议这个功能的。在预览接口这个功能时，能默认上一次操作嘛。这样成本小点，用户体验也好。不用每次都得重新设置。
