### ISSUE TITLE
部分问题系列

### ISSUE THREAD

**Issue by Jairwin-L** [MarvenGong/fastmock#29]
1. 如果这里连续性按ctrl+s保存，好像有问题？会同时出来这2个
![image](https://user-images.githubusercontent.com/32570960/117814811-6210b500-b297-11eb-993f-9f08646ec675.png)

2. 这里校验，有问题：输入0再删除会出现红色文字警告提示，应该是输入的时候再校验
![image](https://user-images.githubusercontent.com/32570960/117815063-a69c5080-b297-11eb-88d6-cbb31c8a6ca3.png)

3. 原密码的placeholder和错误文案提示不一致，而且点击右上角关闭按钮表单没有清空
![image](https://user-images.githubusercontent.com/32570960/117815097-ae5bf500-b297-11eb-8393-e60bb9c80e83.png)

**Comment by MarvenGong** [comment]
已处理
