### ISSUE TITLE
mock语法的不支持

### ISSUE THREAD

**Issue by Jerry-Hero666** [MarvenGong/fastmock#38]
{
    "data": [function() {
    Mock.mock({
        "array|5": [{
          "id|+1":0
        }]
      }).array.forEach(item=>{
        this.push(item)
      })
     return this.pop()
  }]
}
这段代码在mock中是运行的，但是在fastmock中一直报错，是因为什么？
在fastmock中 我是这样的写的：
{
  "data": [function({
    Mock
  }) {
    Mock.mock({
        "array|5": [{
          "id|+1":0
        }]
      }).array.forEach(item=>{
        this.push(item)
      })
       return this.pop()
     
  }]
}

**Comment by MarvenGong** [comment]
看您的代码应该是需要这样的返回：
{
  "data": function({Mock}) {
    return Mock.mock({
      "array|5": [{
        "id|+1": 0
      }]
    })
  }
}
