### ISSUE TITLE
query参数的值转变成对象出错

### ISSUE THREAD

**Issue by lzus** [MarvenGong/fastmock#52]
如果filter的值是{"id":"123456"}，想把它转变成json对象，下面的语句保存时会出错，如何解决呢
{
  "code": "0000",
  "data": {
    "userInfo": function({_req, Mock}) {
      let o = JSON.parse(_req.query.filter);
      return null;
    },
  },
  "desc": "成功"
}

**Comment by MarvenGong** [comment]
在函数内使用JSON.parse 现在是会导致错误，后面看有没有办法处理下
