### ISSUE TITLE
【Bugfix】不兼容微信小程序IDE工具发起的请求

### ISSUE THREAD

**Issue by Youziz** [MarvenGong/fastmock#55]
【Bugfix】不兼容微信小程序IDE工具发起的请求，会一直pengding中，使用其他接口是正常的

**Comment by MarvenGong** [comment]
本地开发需要再微信开发者工具配置不检查接口域名。生产或体验版需要配置域名白名单




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MarvenGong/fastmock"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月15日(星期一) 下午2:33
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[MarvenGong/fastmock] 【Bugfix】不兼容微信小程序IDE工具发起的请求 (Issue #55)





 
【Bugfix】不兼容微信小程序IDE工具发起的请求，会一直pengding中，使用其他接口是正常的

**Comment by Youziz** [comment]
和白名单无关，如果是白名单问题，IDE会自己abort拒绝请求的，猜测是服务端响应预请求的头文件标识有问题，导致请求未被正常结束

**Comment by MarvenGong** [comment]
您是小程序还是公众号请求呢，我这边请求是正常的呢
<img width="1361" alt="image" src="https://github.com/MarvenGong/fastmock/assets/12905440/a1ca0aed-9542-45ac-b15f-638c037cfa3c">
~~~js
wx.request({
  url: 'https://www.fastmock.site/mock/2c8839b182b4d4f0658dcb8a528013d5/tes/app/products',
  method: 'GET',
  success(res) {
	  console.log(res);
  },
  fail(err) {
	  console.error(err);
  }
})
~~~


> 和白名单无关，如果是白名单问题，IDE会自己abort拒绝请求的，猜测是服务端响应预请求的头文件标识有问题，导致请求未被正常结束

**Comment by Youziz** [comment]
非常抱歉！
之前是用Post的场景出现状态一直pending，今天参数未复现，后续如果有复现该问题，我用邮件截图反馈吧
Thanks♪(･ω･)ﾉ

￼
