### ISSUE TITLE
关于接口标签页分页的bug

### ISSUE THREAD

**Issue by TheYellowDuckWithRedBottle** [MarvenGong/fastmock#57]
![image](https://github.com/MarvenGong/fastmock/assets/40554120/26a3198e-0394-4ccc-820b-154a0187e5f4)
如果这时切换到了另一个分页就会查不到另一个标签tab页的数据，目测是传参的时候传的是上一个分页的页数导致的
![image](https://github.com/MarvenGong/fastmock/assets/40554120/383d3ecb-9b5e-48fb-9baa-9b9ff153154a)

**Comment by MarvenGong** [comment]
已处理
